---
- name: Check namespace doesn't already exist
  shell: oc get namespace {{ namespace }}
  register: namespace_exists
  failed_when: namespace_exists.stderr != '' and 'NotFound' not in namespace_exists.stderr

- name: Create namespace {{ namespace }} if it doesnt exist
  shell: oc create namespace {{ namespace }}
  when: namespace_exists.rc != 0

- name: Give namespace {{ namespace }} display name {{ che_display_name }}
  shell: oc annotate --overwrite namespace {{ namespace }} openshift.io/display-name="{{ che_display_name }}"
