---
- include_tasks: ./create_grafanadashboards.yml
- include_tasks: ./create_alerts.yml
- include_tasks: ./prometheus_additional_scrape_config.yml
- include_tasks: ./create_blackboxtargets.yml
- include_tasks: ./patch_blackboxtargets_config.yml
  when: not eval_self_signed_certs|bool
- include_tasks: ./create_alertmanager.yml 

