---
# defaults file for che

#common vars
che_namespace: "{{ eval_che_namespace | default('codeready') }}"
che_display_name: "Red Hat CodeReady"
che_template_folder: /tmp/che-templates
che_validate_certs: "{{ eval_sso_validate_certs | default('true') }}"

#server template vars
che_protocol: https
che_ws_protocol: wss
che_multiuser: true
che_tls: true
che_keycloak_realm: ''
che_keycloak_client_id: 'che-client'
che_keycloak_host: '{{che_protocol}}://{{eval_launcher_sso_host}}'

#pvc vars
che_persistent_volume: true
che_persistent_volume_size: 1Gi
che_persistent_volume_storageclassname: efs

#postgre
che_postgre_image_name: 'docker.io/eclipse/che-postgres'
che_postgre_image_tag: '6.9.0'

#keycloak
che_keycloak_user: admin
che_keycloak_password: admin
che_keycloak_image_tag: '6.9.0'
che_keycloak_image_name: 'docker.io/eclipse/che-keycloak'
che_keycloak_require_update_password: true
che_keycloak_update_password: 'admin'
che_keycloak_port: 443

#backup
codeready_backup_postgres_secret: 'codeready-postgres-secret'
codeready_postgres_cronjob_name: 'codeready-postgres-backup'
codeready_pv_cronjob_name: 'codeready-pv-backup'
