---
- name: Apply resource overrides for enmasse
  include_role:
    name: resource_limits
  vars:
    ns: "{{ enmasse_namespace }}"
    resources: "{{ enmasse_resources }}"
  when: (enmasse_resources | d([], true) | length) > 0
