gitea_namespace: gitea
gitea_git_ref: release-9.28.0
gitea_operator_image_url: quay.io/integreatly/gitea-operator
gitea_operator_image_tag: release-9.28.0
gitea_resources:
  - https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_git_ref}}/deploy/service_account.yaml
  - https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_git_ref}}/deploy/role.yaml
  - https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_git_ref}}/deploy/role_binding.yaml
  - https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_git_ref}}/deploy/crds/crd.yaml

webapp_namespace: webapp
gitea_admin_username: giteaadmin
gitea_admin_token: admintoken
gitea_admin_password: Password1
