gitea_namespace: gitea
gitea_resource_tag: master # Will need to point at tagged version
gitea_resources:
  - https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_resource_tag}}/deploy/service_account.yaml
  - https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_resource_tag}}/deploy/role.yaml
  - https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_resource_tag}}/deploy/role_binding.yaml
  - https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_resource_tag}}/deploy/crds/crd.yaml
  - https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_resource_tag}}/deploy/operator.yaml

webapp_namespace: webapp
gitea_admin_username: giteaadmin
gitea_admin_token: admintoken
gitea_admin_password: Password1