gitea_namespace: gitea

gitea_operator_resource_items:
  - "{{ gitea_operator_resources }}/service_account.yaml"
  - "{{ gitea_operator_resources }}/role.yaml"
  - "{{ gitea_operator_resources }}/role_binding.yaml"
  - "{{ gitea_operator_resources }}/crds/crd.yaml"
  - "{{ gitea_operator_resources }}/operator.yaml"

webapp_namespace: "{{ eval_webapp_namespace | default('webapp') }}"
gitea_admin_username: giteaadmin
gitea_admin_token: admintoken
gitea_admin_password: Password1

gitea_prometheusrule_name: gitea-prometheusrule
