---
# defaults file for walkthroughs
crud_spboot_image_tag: "51e5091"
crud_spboot_runtime_version: 1.3-8
crud_spboot_source_repo_url: "https://github.com/integr8ly/spboot-example.git"
crud_spboot_source_repo_ref: "51e5091"
crud_spboot_source_repo_dir: "."
crud_spboot_artifact_copy_args: "'*.jar'"
crud_spboot_github_webhook_secret: ""
crud_spboot_maven_mirror_url: ""

msg_work_queue_node_image_tag: "v5.0.0"
msg_work_queue_node_source_repo_url: "https://github.com/integr8ly/nodejs-messaging-work-queue.git"
msg_work_queue_node_source_repo_dir: "frontend"
msg_work_queue_node_github_webhook_secret: ""

msg_work_queue_node_service_name: messaging-service
msg_work_queue_node_service_host: messaging.enmasse-eval.svc
msg_work_queue_node_service_port: "5672"
msg_work_queue_node_service_user: "username"
msg_work_queue_node_service_password: "password"

location_soap_source_repo_url: "https://github.com/integr8ly/location-soap.git"
location_soap_source_repo_ref: "4c97875"
