---
- hosts: master
  gather_facts: no
  tasks:
    - name: Retrieve cluster route subdomain
      slurp:
        src: "{{ eval_openshift_master_config_path }}"
      register: openshift_master_config
      become: yes

    - add_host:
        name: GITEA_VARS
        cluster_route_subdomain: "{{ (openshift_master_config['content'] | b64decode | from_yaml)['routingConfig']['subdomain'] }}"

- name: Install Gitea
  hosts: local
  gather_facts: no
  roles:
    - role: gitea
      vars:
        gitea_route_suffix: "{{ hostvars['GITEA_VARS']['cluster_route_subdomain'] }}"
