---
- hosts: localhost
  gather_facts: no
  roles:
  - role: middleware_monitoring
    when: middleware_monitoring | default(true) | bool
  - role: middleware_monitoring_config
    when: middleware_monitoring | default(true) | bool