---
- hosts: master
  gather_facts: no
  tasks:
    - name: Retrieve master public URL
      slurp:
        src: "{{ rhsso_openshift_master_config_path | default(eval_openshift_master_config_path) }}"
      register: rhsso_master_config
      become: yes

    - add_host:
        name: RHSSO_VARS
        openshift_master_url: "{{ (rhsso_master_config['content'] | b64decode | from_yaml)['masterPublicURL'] }}"
        openshift_route_suffix: "{{ (rhsso_master_config['content'] | b64decode | from_yaml)['routingConfig']['subdomain'] }}"
    
- hosts: local
  gather_facts: no
  roles:
    - role: rhsso
      vars:
        rhsso_redirect_uri: "{{ hostvars['RHSSO_VARS']['openshift_master_url'] }}"
        apps_redirect_uri: "{{ hostvars['RHSSO_VARS']['openshift_route_suffix'] }}"
  tasks:
    - include_role:
        name: rhsso
        tasks_from: logout
      vars:
        rhsso_redirect_uri: "{{ hostvars['RHSSO_VARS']['openshift_master_url'] }}"

- hosts: master
  gather_facts: no
  tasks:
    - include_role:
        name: rhsso
        tasks_from: identityprovider