---
- hosts: localhost
  tasks:
    - 
      when: keep_namespaces is undefined or not keep_namespaces | bool
      block:
        - 
          name: Check that the jq exists
          stat:
            path: /usr/bin/jq
          failed_when: false
          register: jq_binary

        - 
          name: download jq
          become: true
          get_url:
            url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
            dest: /usr/bin/jq
            mode: 0555
          when: jq_binary.stat.exists == False 

        - 
          name: Get namespaces to clean up
          shell: oc get namespaces -o json | jq '.items[] | select(.metadata.annotations["openshift.io/requester"] != null and .metadata.annotations["openshift.io/requester"] != "system:admin") | .metadata.name' | cut -f2 -d'"'
          register: namespaces_output
        -
          name: Delete namespaces
          shell: "oc delete namespace {{ item }}"
          with_items: "{{ namespaces_output.stdout_lines }}"
    -
      name: Uninstall launcher
      include_role:
        name: launcher
        tasks_from: uninstall
      tags: ['launcher']
    -
      name: Uninstall che
      include_role:
        name: che
        tasks_from: uninstall
      vars:
        delete_keycloak_user: false
        che_delete_namespace: true
      tags: ['che']
    - 
      name: Uninstall managed services broker
      include_role:
        name: msbroker
        tasks_from: uninstall
      tags: ['msbroker']
    - 
      name: Uninstall 3scale
      include_role:
        name: 3scale
        tasks_from: uninstall
      tags: ['3scale']
    - 
      name: Uninstall Gitea
      include_role:
        name: gitea
        tasks_from: uninstall
      tags: ['gitea']
    - 
      name: "Delete enmasse cluster service broker"
      shell: oc delete clusterservicebroker enmasse
      register: output
      failed_when: output.stderr != '' and 'not found' not in output.stderr
    - 
      name: "Delete project namespace: {{ enmasse_namespace }}"
      shell: oc delete project {{ enmasse_namespace }}
      register: output
      failed_when: output.stderr != '' and 'not found' not in output.stderr and 'The system is ensuring all content is removed from this namespace.' not in output.stderr
      changed_when: output.rc == 0
    - 
      name: Delete users
      shell: oc delete user admin@example.com evals@example.com
    - 
      name: Uninstall the webapp
      include_role:
        name: webapp
        tasks_from: uninstall
      tags: ['webapp']
    - 
      name: Uninstall rhsso
      include_role:
        name: rhsso
        tasks_from: uninstall
      tags: ['rhsso']
    - name: Uninstall Nexus
      include_role:
        name: nexus
        tasks_from: uninstall
      tags: ['nexus']
- hosts: master
  tasks:
    - 
      name: Uninstall rhsso
      include_role:
        name: rhsso
        tasks_from: reconfigure_master
      tags: ['rhsso']
