---
integreatly_version: release-1.10.0

# threescale version is controlled by the operator. Changing the operator version will change the 3scale version

# controls whether threescale is installed or not.
threescale: True
# below threescale variables below are not currently used. They def ine where and what to pull in from github. These will be important as we look to break out and decouple the resources from the installer ###############
# not currently used but records the version installed by the operator, this should come from the status block
threescale_version: '2.10.0.GA'
threescale_namespace: "{{ns_prefix | default('')}}3scale"
threescale_display_name: "Red Hat 3scale API Management Platform"
threescale_resources_base: 'https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/{{threescale_version}}/amp'
threescale_template: '{{threescale_resources_base}}/amp.yml'
threescale_template_s3: '{{threescale_resources_base}}/amp-s3.yml'

#controls whether che is installed or not
#note che cannot be installed without launcher being present currently
che: True
che_version: '2.0.0.GA'
che_git_url: https://github.com/redhat-developer/codeready-workspaces-deprecated.git

#controls whether enmasse is installed or not
enmasse: True
enmasse_version: '1.5.2.GA'
enmasse_git_url: https://github.com/jboss-container-images/amq-online-images.git
enmasse_postgresql_image: 'postgresql:9.6'

#controls whether fuse is installed or not
fuse: True
#This is the release tag for fuse on openshift in github currently used to pull in the templates and image streams
fuse_release_tag: 'application-templates-2.1.0.fuse-760043-redhat-00003'
#Used in customisation role to specify fuse version
fuse_version: '7.6.0'

#controls whether Fuse Online is installed or not
fuse_online: True
# Syndesis operator version to be installed
fuse_online_release_tag: '1.9.15'
#Imagestream version installed by syndesis operator
fuse_online_operator_imagestream_version: '1.6'
# Used by msbroker
fuse_online_resources_base: 'https://raw.githubusercontent.com/integr8ly/fuse-online-install/{{fuse_online_release_tag}}/resources'
fuse_online_binary_resources_base: https://github.com/jboss-fuse/fuse-clients/releases/download/{{fuse_online_release_tag}}/syndesis-{{fuse_online_release_tag}}-linux-64bit.tar.gz
fuse_online_crd_resources: '{{fuse_online_resources_base}}/syndesis-crd.yml'

#controls whether Launcher is installed or not.
launcher: True
# https://github.com/fabric8-launcher/launcher-openshift-templates/issues/46
# we will need to set this during a release to the latest commit hash on master to ensure it doesn't change under us example: c1efdf1
launcher_backend_image_tag: '7a7fd07'
# we will need to set this during a release to the latest commit hash on master to ensure it doesn't change under us example: 0a941c1
launcher_frontend_image_tag: '4e404a1'
launcher_creator_backend_image_tag: 'e10cf46'
launcher_version: '7224e235226ffa42135f148bacc409e9f7f402e4'
launcher_template: 'https://raw.githubusercontent.com/fabric8-launcher/launcher-openshift-templates/{{launcher_version}}/openshift/launcher-template.yaml'
launcher_sso_imagestream_name: redhat-sso73-openshift:1.0
launcher_sso_imagestream_image: registry.redhat.io/redhat-sso-7/sso73-openshift:1.0
launcher_sso_template: https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.3.2.GA/templates/sso73-x509-postgresql-persistent.json

#not currently used but is the version installed by the operator
# rhsso is not an optional component
rhsso_version: '7.4.2.GA'
#below vars not currently used but will be used to pull in the new versions of RH-SSO once we decouple the resources from the installer.
rhsso_imagestream_name: redhat-sso74-openshift:1.0
rhsso_imagestream_image:  registry.redhat.io/rh-sso-7/sso74-openshift-rhel8
rhsso_operator_release_tag: 'v1.10.2'
rhsso_operator_resources: 'https://raw.githubusercontent.com/integr8ly/keycloak-operator/{{rhsso_operator_release_tag}}/deploy/'

#controls whether gitea is installed or not
gitea: False
gitea_version: '1.10.3'
#below vars are not currently used but will be used once we source resources from outside of the installer
gitea_operator_release_tag: 'v0.0.5'
gitea_operator_resources: 'https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_operator_release_tag}}/deploy/'

#controls whether webapp is installed or not
webapp: True
#below vars are not currently used but reflect the current state. In the future they will be used when we source resources from outside of the installer
webapp_version: '2.28.1'
webapp_operator_release_tag: 'v0.0.63'
webapp_operator_resources: 'https://raw.githubusercontent.com/integr8ly/tutorial-web-app-operator/{{webapp_operator_release_tag}}/deploy'

#controls whether apicurito is installed or not
apicurito: True
apicurito_version: '0.2.18.Final'

#controls whether nexus is installed or not
nexus: False
nexus_version: '2.14.11-01'

## Enables datasync templates (enabled by default)
datasync: True
datasync_template_tag: '0.9.4'

rhsso_user_operator_resources: "{{ rhsso_operator_resources }}"

#unifiedpush
ups: True
ups_operator_release_tag: '0.4.4'
ups_operator_resources: 'https://raw.githubusercontent.com/aerogear/unifiedpush-operator/{{ups_operator_release_tag}}/deploy'
ups_operator_image: 'quay.io/aerogear/unifiedpush-operator:{{ ups_operator_release_tag }}'
ups_release_tag: '2.3.2-1'
ups_image: 'quay.io/aerogear/unifiedpush-configurable-container:{{ ups_release_tag }}'
ups_proxy_release_tag: 'v1.1.0'
ups_proxy_image: 'docker.io/openshift/oauth-proxy:{{ ups_proxy_release_tag }}'

#application metrics
application_metrics: False

#mobile
mobile_walkthrough_tag: '0.7.1'
mobile_walkthrough_location: 'https://github.com/aerogear/mobile-walkthrough#{{ mobile_walkthrough_tag }}'

monitoring_label_name: 'monitoring-key'
monitoring_label_value: 'middleware'
middleware_monitoring_operator_release_tag: '0.0.30'
middleware_monitoring_operator_resources: 'https://raw.githubusercontent.com/integr8ly/application-monitoring-operator/{{ middleware_monitoring_operator_release_tag }}/deploy'

msbroker_release_tag: 'v0.0.15'
msbroker_template: 'https://raw.githubusercontent.com/integr8ly/managed-service-broker/{{ msbroker_release_tag }}/templates/broker.template.yaml'

#AMQ Streams
amq_streams: False
amq_streams_repo_url: https://github.com/jboss-container-images/amqstreams-1-openshift-image
amq_version: 1.1.0

# information about backups
backup_version: '1.0.16'
backup_resources_location: 'https://raw.githubusercontent.com/integr8ly/backup-container-image/{{ backup_version }}/templates/openshift'
backup_image: quay.io/integreatly/backup-container:{{ backup_version }}
backup_schedule: '30 2 * * *'
backup_namespace: "openshift-integreatly-backups"

#Heimdall
heimdall: False
heimdall_operator_release_tag: 'release-1.0.1'
heimdall_operator_resources: 'https://raw.githubusercontent.com/integr8ly/heimdall/{{heimdall_operator_release_tag}}/deploy'

# Supported oc versions
supported_oc_versions:
  - "3.11"
