---
launcher_namespace: "{{ eval_launcher_namespace | default('launcher') }}"

launcher_frontend_image_tag: a00064f

launcher_sso_serviceclass: sso72-x509-postgresql-persistent
launcher_sso_serviceinstance_name: launcher-sso-instance
launcher_sso_username: admin
launcher_sso_password: admin
launcher_sso_plan: default
launcher_sso_realm: launcher_realm
launcher_sso_prefix: launcher-sso
launcher_sso_validate_certs: "{{ eval_sso_validate_certs | default('true') }}"

launcher_sso_admin_username: launcheradmin
launcher_sso_admin_email: launcheradmin@example.com
launcher_sso_admin_password: admin

launcher_sso_openshift_idp_scope: user:full
launcher_sso_openshift_idp_client_id: launcher

launcher_sso_image_stream: redhat-sso72-openshift
launcher_sso_image_stream_tag: "1.1"
launcher_sso_force_image_streams_update: true

launcher_openshift_sso_route: ""
launcher_openshift_sso_realm: "openshift"
launcher_openshift_sso_username: "admin"
launcher_openshift_sso_password: "admin"

launcher_sso_keycloak_client_id: launcher-openshift-users

launcher_github_default_scopes: "admin:repo_hook,read:org,public_repo"

launcher_catalog_git_repo: https://github.com/integr8ly/launcher-booster-catalog
launcher_catalog_git_ref: master

github_repo_description: "Generated by Red Hat Developer Launch"

github_client_id: "set_to_client_id_of_github_oauth_app"
github_client_secret: "set_to_client_secret_of_github_oauth_app"
