---
rhsso_keycloak_operator_image_url: "quay.io/integreatly/keycloak-operator"
rhsso_keycloak_operator_image_tag: release-release-1.2.0-rc4

rhsso_namespace: "{{ eval_rhsso_namespace | default('sso') }}"

rhsso_admin_username: admin
rhsso_admin_realm: master
rhsso_realm: openshift
rhsso_realm_event_listeners:
  - metrics-listener
rhsso_client_id: openshift-client
rhsso_validate_certs: "{{ eval_sso_validate_certs | default('true') }}"
rhsso_redirect_uri: ""

rhsso_openshift_master_config_path: /etc/origin/master/master-config.yaml
rhsso_hide_default_identity_providers: true

rhsso_identity_provider_self_signed_certs: "{{ eval_self_signed_certs | default(true) }}"
rhsso_identity_provider_ca_cert_path: ca.crt
rhsso_master_restart_shim_path: /usr/local/bin/master-restart

rhsso_openshift_webconsole_namespace: openshift-web-console
rhsso_openshift_webconsole_configmap: webconsole-config
rhsso_openshift_update_webconsole_configmap: false

rhsso_operator_repo: integr8ly
rhsso_operator_commit_tag: release-release-1.2.0-rc4

rhsso_operator_required_objects:
  - rbac.yaml

rhsso_operator_required_crd_objects:
  - Keycloak_crd.yaml
  - KeycloakRealm_crd.yaml

rhsso_seed_users_email_format: evals%02d@example.com
rhsso_seed_users_name_format: evals%02d
rhsso_seed_users_count: "{{ eval_seed_users_count }}"
rhsso_seed_users_password: Password1

rhsso_evals_email: evals@example.com  
rhsso_evals_username: "{{ rhsso_evals_email }}" 
rhsso_evals_password: Password1

rhsso_evals_admin_email: customer-admin@example.com
rhsso_evals_admin_username: customer-admin
rhsso_evals_admin_password: Password1

rhsso_cluster_admin_email: admin@example.com
rhsso_cluster_admin_username: admin
rhsso_cluster_admin_password: Password1

rhsso_plugins:
  - keycloak-metrics-spi
  
original_identity_provider_path: /tmp/original_identity_provider_config
