---
rhsso_namespace: "{{ eval_rhsso_namespace | default('sso') }}"
rhsso_template: sso72-x509-postgresql-persistent
rhsso_template_filename: sso72-x509-postgresql-persistent.json
rhsso_template_url: https://raw.githubusercontent.com/jboss-openshift/application-templates/ose-v1.4.11/sso/

rhsso_image_stream: redhat-sso72-openshift
rhsso_image_stream_filename: sso72-image-stream.json
rhsso_image_stream_tag: "1.1"
rhsso_force_image_streams_update: true

rhsso_admin_username: admin
rhsso_admin_realm: master
rhsso_realm: openshift
rhsso_client_id: openshift-client
rhsso_validate_certs: "{{ eval_sso_validate_certs | default('true') }}"
rhsso_redirect_uri: ""

rhsso_evals_email: evals@example.com
rhsso_evals_username: "{{ rhsso_evals_email }}"
rhsso_evals_password: Password1

rhsso_evals_admin_email: evals-admin@example.com
rhsso_evals_admin_username: "{{ rhsso_evals_admin_email }}"
rhsso_evals_admin_password: Password1

rhsso_seed_users_email_format: evals%02d@example.com
rhsso_seed_users_name_format: evals%02d@example.com
rhsso_seed_users_count: 50
rhsso_seed_users_password: Password1

rhsso_cluster_admin_email: admin@example.com
rhsso_cluster_admin_username: "{{ rhsso_cluster_admin_email }}"
rhsso_cluster_admin_password: Password1

rhsso_openshift_master_config_path: /etc/origin/master/master-config.yaml
rhsso_disable_htpasswd_identity_provider: true

rhsso_identity_provider_self_signed_certs: "{{ eval_self_signed_certs | default(true) }}"
rhsso_identity_provider_ca_cert_path: ca.crt
rhsso_master_restart_shim_path: /usr/local/bin/master-restart

rhsso_openshift_webconsole_namespace: openshift-web-console
rhsso_openshift_webconsole_configmap: webconsole-config
rhsso_openshift_update_webconsole_configmap: false