---

- name: Create backup ServiceAccount
  shell: oc create -f {{backup_resources_location}}/rbac/service-account.yaml -n {{ serviceaccount_namespace }}
  register: backup_sa_create
  failed_when: backup_sa_create.stderr != '' and 'AlreadyExists' not in backup_sa_create.stderr

- template:
    src: backup-role-binding.yml.j2
    dest: /tmp/backup-role-binding.yml
  vars:
    name: '{{ binding_name }}'

- name: Create backup role binding
  shell: oc create -f /tmp/backup-role-binding.yml -n {{ serviceaccount_namespace }}
  register: backup_rolebinding_create
  failed_when: backup_rolebinding_create.stderr != '' and 'AlreadyExists' not in backup_rolebinding_create.stderr
