---
- name: Update expected cronjobs
  set_fact:
    backup_expected_cronjobs: "{{ backup_expected_cronjobs | combine(sso_expected_cronjobs) }}"
  when: user_rhsso | default(true) | bool

- template:
    src: backup-monitoring-alerts.yml.j2
    dest: /tmp/backup-monitoring-alerts.yml
  vars:
    expected_cronjobs: "{{ backup_expected_cronjobs }}"

- name: Create CronJob Alerts
  shell: oc apply -f /tmp/backup-monitoring-alerts.yml -n {{ monitoring_namespace }}
  register: create_alerts
  failed_when: create_alerts.rc != 0
