---
rhsso_user_tmp_dir: /tmp
rhsso_user_namespace: "{{ eval_user_rhsso_namespace | default('user-sso') }}"
rhsso_user_mdc_namespace: "{{ eval_mdc_namespace | default('mobile-developer-console') }}"
rhsso_user_rbac_name: mdc-account-keycloak-operator
rhsso_user_client_id: user-sso

rhsso_user_resources:
  - name: sso
    kind: dc
    resources:
      requests:
        memory: 500Mi
  - name: sso-postgresql
    kind: dc
    resources:
      requests:
        memory: 25Mi
