---

#Walkthrough 2 routes
- name: Create evaluation user wt2 route
  import_tasks: _wt2_route.yml email={{ threescale_evals_email }}

- name: Create evaluation admin user wt2 route
  import_tasks: _wt2_route.yml email={{ rhsso_evals_admin_email }}

- name: Seed evaluation users wt2 routes
  import_tasks: _wt2_route.yml email={{ rhsso_seed_users_email_format|format(item|int) }}
  with_sequence: count={{ rhsso_seed_users_count }}

#Walkthrough 3 routes
- name: Create evaluation user wt3 route
  import_tasks: _wt3_route.yml email={{ threescale_evals_email }}

- name: Create evaluation admin user wt3 route
  import_tasks: _wt3_route.yml email={{ rhsso_evals_admin_email }}

- name: Seed evaluation users wt3 routes
  import_tasks: _wt3_route.yml email={{ rhsso_seed_users_email_format|format(item|int) }}
  with_sequence: count={{ rhsso_seed_users_count }}
