---
mdc_template_dir: /tmp
mdc_namespace: mobile-developer-console
mdc_name: mdc
mdc_oauth_client_id: mobile-developer-console
mdc_resources:
  - "{{ mdc_operator_resources }}/service_account.yaml"
  - "{{ mdc_operator_resources }}/role.yaml"
  - "{{ mdc_operator_resources }}/role_binding.yaml"
  - "{{ mdc_operator_resources }}/crds/mdc_v1alpha1_mobiledeveloperconsole_crd.yaml"
  - "{{ mdc_operator_resources }}/mobileclient_admin_role.yaml"
  - "{{ mdc_operator_resources }}/mdc_v1alpha1_mobileclient_crd.yaml"
mdc_openshift_master_config_path: "{{ eval_openshift_master_config_path | default('/etc/origin/master/master-config.yaml') }}"