---
- name: Get Launcher dashboard url
  shell: oc get route/launcher -o jsonpath='{.spec.host}' -n {{ launcher_namespace }}
  register: launcher_host_cmd
- set_fact:
    launcher_dashboard_url: "http://{{ launcher_host_cmd.stdout}}"

- name: Get Che dashboard url
  shell: oc get route/che -o jsonpath='{.spec.host}' -n {{ che_namespace }}
  register: che_host_cmd
- set_fact:
    che_dashboard_url: "https://{{ che_host_cmd.stdout}}"

# Create managed-services-broker namespace
- name: Check if {{ msbroker_namespace }} namespace exists
  shell: oc get namespace {{ msbroker_namespace }}
  failed_when: false
  register: msbroker_check_namespace_exists

- name: Create managed services broker namespace
  shell: oc new-project {{ msbroker_namespace }}
  when: msbroker_check_namespace_exists.rc != 0

- name: Create Required CRDs
  shell: "oc create -f {{ item }}"
  register: output
  failed_when: output.stderr != '' and 'already exists' not in output.stderr
  changed_when: output.rc == 0
  with_items: "{{ required_crds }}"

# Create RBAC
- name: Check if rbac roles exists
  shell: oc get -f {{ msbroker_rbac_url }} -n {{ msbroker_namespace }}
  register: check_rbac_exist
  failed_when: false

- set_fact:
    total_roles: 4 # Total number of roles that is in rbac.yml
    total_roles_found: "{{ (check_rbac_exist.stdout_lines | length) / 2 }}" # Total number of roles that already exists

- set_fact:
    num_roles_to_create: "{{ total_roles - (total_roles_found | int) }}"

- name: Create RBAC for the managed services broker
  shell: oc create -f {{ msbroker_rbac_url }} -n {{ msbroker_namespace }}
  register: create_rbac_result
  failed_when: (num_roles_to_create | int) != (create_rbac_result.stdout_lines | length) # Only fail when the number of roles to be created doesn't match the total number of what's actually created

# Deploy managed service broker
- name: Check if managed service broker already exists in {{ msbroker_namespace }}
  shell: oc get deployment/msb -n {{ msbroker_namespace }}
  register: msbroker_exists_cmd
  failed_when: false

- name: Create managed service broker template in {{ msbroker_namespace }}
  shell: oc process -n {{ msbroker_namespace }} -f {{ msbroker_template_url }} --param=ROUTE_SUFFIX={{ route_suffix }} --param=LAUNCHER_DASHBOARD_URL={{ launcher_dashboard_url }} --param=CHE_DASHBOARD_URL={{ che_dashboard_url }} --param=IMAGE_ORG={{ msbroker_image_org }} | oc create -n {{ msbroker_namespace }} -f -
  when: msbroker_exists_cmd.rc != 0