---
middleware_monitoring_namespace: "{{ns_prefix | default('')}}middleware-monitoring"
openshift_monitoring_namespace: openshift-monitoring
threescale_namespace: "{{ns_prefix | default('')}}3scale"

jobs:
- 3scale
- openshift_monitoring_federation

config_secret_contents_file: integreatly-additional.yaml
prometheus_cr_name: application-monitoring
additional_scrape_config_name: integreatly-additional-scrape-configs
additional_scrape_config_patch: "{\"spec\":{\"additionalScrapeConfigs\":{\"name\":\"{{ additional_scrape_config_name }}\", \"key\": \"{{ config_secret_contents_file }}\"}}}"

# GrafanaDashboards template variables
monitoring_conf_tmp_dir: /tmp
monitoring_grafanadashboards_resource_templates:
- endpointsdetailed.yml
- endpointsreport.yml
- endpointssummary.yml
- resources-by-namespace.yml
- resources-by-pod.yml
- cluster-resources.yml

heimdall_grafanadashboards_template:
- images_cves.yml

# PrometheusRules template variables
monitoring_prometheusrules_resource_templates:
- kube_state_metrics_alerts.yml

# BlackboxTargets template variables
monitoring_blackboxtargets_resource_templates:
- blackboxtargets.yml