---
middleware_monitoring_namespace: "{{ns_prefix | default('')}}middleware-monitoring"
openshift_monitoring_namespace: openshift-monitoring
threescale_namespace: "{{ns_prefix | default('')}}3scale"

jobs:
- 3scale
- openshift_monitoring_federation

config_secret_contents_file: integreatly-additional.yaml
prometheus_cr_name: application-monitoring
additional_scrape_config_name: integreatly-additional-scrape-configs
additional_scrape_config_patch: "{\"spec\":{\"additionalScrapeConfigs\":{\"name\":\"{{ additional_scrape_config_name }}\", \"key\": \"{{ config_secret_contents_file }}\"}}}"

# GrafanaDashboards template variables
monitoring_conf_tmp_dir: /tmp
monitoring_grafanadashboards_resource_templates:
- endpointsdetailed.yml
- endpointsreport.yml
- endpointssummary.yml
- resources-by-namespace.yml
- resources-by-pod.yml
- cluster-resources.yml

heimdall_grafanadashboards_template:
- images_cves.yml

# PrometheusRules template variables
monitoring_prometheusrules_resource_templates:
- kube_state_metrics_alerts.yml
- kube_state_metrics_3scale_alerts.yml
- kube_state_metrics_fuse_online_alerts.yml

# BlackboxTargets template variables
monitoring_blackboxtargets_resource_templates:
- blackboxtargets.yml

# Alertmanager template variables
alertmanager_to_email: "{{ cluster_mailto | default('blank@example.com') }}"

# Sengrid Defaults
smtp_smarthost: smtp.sendgrid.net:587
smtp_auth_username: apikey
smtp_auth_password: "{{ sendgrid_api_key | default('') }}"

# DMS
dms_webhook_url: "{{ deadmanssnitch_url | default('') }}"

# pagerduty
pd_service_key: "{{ pagerduty_integration_key | default('') }}"
