-
  name: Check if secure route exists
  shell: oc get route/che -o template --template \{\{.spec.tls\}\} -n {{ che_namespace }}
  register: che_route_cmd
  failed_when: false
  when: che_protocol == 'https'

-
  name: Deploy secure che server route
  block:
    -
      name: Delete non-secure route
      shell: "oc delete route/che -n {{ che_namespace }}"
      failed_when: false
    -
      name: Create secure route
      shell: "oc apply -f {{ che_template_folder }}/deploy/https/che-route-tls.yaml -n {{ che_namespace }}"
  when: che_route_cmd.stderr != ''
