mobile_security_service_name: "mobile-security-service"
mobile_security_service_namespace: "{{ eval_mobile_security_service_namespace | default('mobile-security-service') }}"
mobile_security_service_display_name: "Mobile Security Service"

mobile_security_service_operator_resource_items:
  - "{{ mobile_security_service_operator_resources }}/crds/mobile-security-service_v1alpha1_mobilesecurityservice_crd.yaml"
  - "{{ mobile_security_service_operator_resources }}/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_crd.yaml"
  - "{{ mobile_security_service_operator_resources }}/crds/mobile-security-service_v1alpha1_mobilesecurityserviceapp_crd.yaml"
  - "{{ mobile_security_service_operator_resources }}/crds/mobile-security-service_v1alpha1_mobilesecurityservicebackup_crd.yaml"
  - "{{ mobile_security_service_operator_resources }}/cluster_role.yaml"
  - "{{ mobile_security_service_operator_resources }}/service_account.yaml"

mobile_security_service_monitoring_resource_items:
  - "{{ mobile_security_service_operator_resources }}/monitor/service_monitor.yaml"
  - "{{ mobile_security_service_operator_resources }}/monitor/mss_service_monitor.yaml"

mobile_security_service_monitoring_resource_templates:
  - mss_grafana_dashboard
  - mss_operator_grafana_dashboard
  - mss_operator_prometheus_rule
  - mss_prometheus_rule

mdc_namespace: "{{ eval_mdc_namespace | default('mobile-developer-console') }}"

mobile_security_service_resources:
  # - name: mobile-security-service
  #   kind: deploy
  #   resources: 
  #     - container: oauth-proxy
  #     - container: application
  #       limits: 
  #         memory: 512Mi
  #       requests: 
  #         memory: 512Mi
  # - name: mobile-security-service-db
  #   kind: deploy
  #   resources: 
  #     limits: 
  #       memory: 512Mi
  #     requests: 
  #       memory: 512Mi
  # - name: mobile-security-service-operator
  #   kind: deploy
