---

- import_tasks: admin_token.yml

- name: Retrieve 3Scale users
  uri:
    url: "https://{{ threescale_admin_route }}/admin/api/users.xml?access_token={{ threescale_admin_token }}"
    method: GET
    return_content: yes
    dest: /tmp/3scale_users.xml
    body: "access_token={{ threescale_admin_token }}"
    validate_certs: "{{ threescale_sso_validate_certs }}"
    status_code: [200]
  register: users_result
  retries: 3
  delay: 2
  until: users_result.status == 503 or users_result.status in [200, 401, 403]

- name: Retrieve default admin user ID
  xml:
    path: /tmp/3scale_users.xml
    xpath: /users/user[username[text()='{{ threescale_cluster_admin_old_username }}']]/id
    content: text
  register: default_admin_user_xml
  ignore_errors: True

- name: Update default admin user account details
  uri:
    url: "https://{{ threescale_admin_route }}/admin/api/users/{{ default_admin_user_xml.matches.0.id|int }}.xml"
    method: PUT
    body: "access_token={{ threescale_admin_token }}&username={{ rhsso_evals_admin_username }}&email={{ rhsso_evals_admin_email }}"
    validate_certs: "{{ threescale_sso_validate_certs }}"
    status_code: [200, 422]
  when: default_admin_user_xml is defined and default_admin_user_xml.matches is defined

- name: Update email address value for system-seed secret
  shell: |
    oc patch secret/system-seed -n {{ threescale_namespace }} -p "{\"stringData\": {\"ADMIN_EMAIL\": \"{{ rhsso_evals_admin_email }}\"}}"

- name: Update username value for system-seed secret
  shell: |
    oc patch secret/system-seed -n {{ threescale_namespace }} -p "{\"stringData\": {\"ADMIN_USER\": \"{{ rhsso_evals_admin_username }}\"}}"

- name: Redeploy system-app
  shell: oc rollout latest system-app -n {{ threescale_namespace }}
  register: result
  failed_when: not result.stdout
  changed_when: False

- name: Verify 3scale deployment succeeded
  shell: sleep 5; oc get pods --namespace {{ threescale_namespace }} | grep  "deploy"
  register: result
  until: not result.stdout
  retries: 50
  delay: 10
  failed_when: result.stdout
  changed_when: False

- name: Seed evaluation users
  include: _user.yml email={{ rhsso_seed_users_email_format|format(item|int) }} username={{ rhsso_seed_users_name_format|format(item|int) }} password={{ rhsso_seed_users_password }}
  with_sequence: count={{ rhsso_seed_users_count }}
