---

# threescale version is controlled by the operator. Changing the operator version will change the 3scale version

# controls whether threescale is installed or not.
threescale: true
# below threescale variables below are not currently used. They define where and what to pull in from github. These will be important as we look to break out and decouple the resources from the installer ###############
# not currently used but records the version installed by the operator, this should come from the status block
threescale_version: '2.4.0.GA'
threescale_template: 'https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/{{threescale_version}}/amp/amp.yml'
threescale_template_s3: 'https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/{{threescale_version}}/amp/amp-s3.yml'

#controls whether che is installed or not
#note che cannot be installed without launcher being present currently
che: true
che_version: '1.0.0.GA'
# by default the GA installer uses the :latest tag so we need to set the tagged version in the config
che_server_image: 'registry.access.redhat.com/codeready-workspaces/server:1.0'
che_installer: 'https://raw.githubusercontent.com/redhat-developer/codeready-workspaces-deprecated/{{che_version}}/operator-installer/deploy.sh'

#controls whether enmasse is installed or not
enmasse: true
enmasse_version: '1.0.0.GA'
# This is used to indicate where to pull the artifact from for installing EnMasse.
enmasse_download_url: https://access.redhat.com/node/3869211/423/0
# Controls whether to use a productised version. Use with 'enmasse_productised_download_url'
is_productised_version: true

#controls whether fuse is installed or not
fuse: true
#This is the release tag for fuse on openshift in github currently used to pull in the templates and image streams
fuse_release_tag: 'application-templates-2.1.fuse-720018-redhat-00001'
#not currently used as the operator decides what to install
fuse_version: '7.2'

#controls whether Fuse Online is installed or not
fuse_online: true
# Below Fuse vars are not currently used but will be used to source the resources needed to do the install.
fuse_online_release_tag: '1.5'
fuse_online_operator_resources: 'https://raw.githubusercontent.com/syndesisio/fuse-online-install/{{fuse_online_release_tag}}/resources/fuse-online-operator.yml'

#controls whether Launcher is installed or not.
launcher: true
# https://github.com/fabric8-launcher/launcher-openshift-templates/issues/46
# we will need to set this during a release to the latest commit hash on master to ensure it doesn't change under us example: c1efdf1
launcher_backend_image_tag: 'b006e49'
# we will need to set this during a release to the latest commit hash on master to ensure it doesn't change under us example: 0a941c1
launcher_frontend_image_tag: 'a00064f'
launcher_version: '7224e235226ffa42135f148bacc409e9f7f402e4'
launcher_template: 'https://raw.githubusercontent.com/fabric8-launcher/launcher-openshift-templates/{{launcher_version}}/openshift/launcher-template.yaml'

#not currently used but is the version installed by the operator
# rhsso is not an optional component
rh_sso_version: '7.2.2.GA'
#below vars not currently used but will be used to pull in the new versions of RH-SSO once we decouple the resources from the installer.
rh_sso_opertor_release_tag: '0.0.2'
rh_sso_operator_resources: 'https://raw.githubusercontent.com/integr8ly/keycloak-operator/{{rh_sso_opertor_release_tag}}/deploy/'

#controls whether gitea is installed or not
gitea: true
gitea_version: '1.6.0' # not currently used for installation reflect current installation (https://github.com/integr8ly/gitea-operator/issues/25)
#below vars are not currently used but will be used once we source resources from outside of the installer
gitea_operator_release_tag: 'v0.0.2'
gitea_operator_resources: 'https://raw.githubusercontent.com/integr8ly/gitea-operator/{{gitea_operator_release_tag}}/deploy/operator.yaml'

#controls whether webapp is installed or not
webapp: true
#below vars are not currently used but reflect the current state. In the future they will be used when we source resources from outside of the installer
webapp_version: '2.3.0'
webapp_operator_release_tag: 'master'
webapp_operator_resources: 'https://raw.githubusercontent.com/integr8ly/tutorial-web-app-operator/{{webapp_operator_release_tag}}/deploy/'

#controls whether apicurito is installed or not
apicurito: true
apicurito_version: '0.2.18.Final'
#controls whether nexus is installed or not
nexus: true
nexus_version: '2.14.11-01'

monitoring_label_name: "monitoring-key"
monitoring_label_value: "middleware"
