#webapp vars
webapp_namespace: "{{ eval_webapp_namespace | default('webapp') }}"
webapp_extra_services_configmap: extra-services
webapp_client_id: tutorial-web-app
webapp_route: tutorial-web-app
webapp_app_label: tutorial-web-app
webapp_operator_template_path: '/home/tutorial-web-app-operator/deploy/template/tutorial-web-app.yml'
webapp_openshift_master_config_path: "{{ eval_openshift_master_config_path | default('/etc/origin/master/master-config.yaml') }}"
webapp_operator_resource_items:
  - "{{ webapp_operator_resources }}/rbac.yaml"
  - "{{ webapp_operator_resources }}/sa.yaml"
  - "{{ webapp_operator_resources }}/crd.yaml"
  - "{{ webapp_operator_resources }}/operator.yaml"
