---
backup_namespace: "openshift-integreatly-backups"

component_backup_secret_namespace: '{{ backup_namespace }}'
backup_resources_cluster:
  - "{{backup_resources_location}}/rbac/role.yaml"

backup_expected_cronjobs: |
  {
    "{{backup_namespace}}": [
      "3scale-mysql-backup",
      "3scale-postgres-backup",
      "3scale-redis-backup",
      "codeready-postgres-backup",
      "codeready-pv-backup",
      "enmasse-postgres-backup",
      "enmasse-pv-backup",
      "fuse-postgres-backup",
      "resources-backup",
      "launcher-postgres-backup"
    ],
    "{{eval_rhsso_namespace}}": [
      "daily-at-midnight-{{eval_rhsso_namespace}}"
    ]
  }

sso_expected_cronjobs: |
  {
    "{{eval_user_rhsso_namespace}}": [
      "daily-at-midnight-{{eval_user_rhsso_namespace}}"
    ]
  }

monitoring_namespace: "{{ns_prefix | default('')}}middleware-monitoring"
