---
- name: Prepare MySQL secret definition
  template:
    src: mysql-secret.yml.j2
    dest: /tmp/mysql-secret.yml
  vars:
    name: '{{ secret_name }}'
    user: '{{ secret_mysql_user }}'
    port: '{{ secret_mysql_port | default("3306") }}'
    host: '{{ secret_mysql_host }}'
    password: '{{ secret_mysql_password }}'

- name: Create MySQL secret {{ secret_name }}
  shell: oc create -f /tmp/mysql-secret.yml -n {{ component_backup_secret_namespace }}
  register: mysql_secret_create
  failed_when: mysql_secret_create.stderr != '' and 'AlreadyExists' not in mysql_secret_create.stderr
