---
- hosts: localhost
  gather_facts: no
  roles:
  - role: middleware_monitoring_config
    when: middleware_monitoring | default(true) | bool
  - role: 3scale_config
    when: middleware_monitoring | default(true) | bool
  tasks:
  - include_role:
      name: gitea
      tasks_from: monitoring
    when:
      - middleware_monitoring | default(true) | bool
      - gitea | default(true) | bool
  - include_role:
      name: webapp
      tasks_from: monitoring
    when:
      - middleware_monitoring | default(true) | bool
      - webapp | default(true) | bool
  - include_role:
      name: mobile_security_service
      tasks_from: monitoring
    when:
      - middleware_monitoring | default(true) | bool
      - mobile_security_service | default(true) | bool
  - include_role:
      name: ups
      tasks_from: monitoring
    when:
      - middleware_monitoring | default(true) | bool
      - ups | default(true) | bool
  - include_role:
      name: mdc
      tasks_from: monitoring
    when:
      - middleware_monitoring | default(true) | bool
      - mdc | default(true) | bool