---
- import_playbook: "./prerequisites.yml"
- import_playbook: "./openshift.yml"
- import_playbook: "./user.yaml"
- import_playbook: "./install_amq_streams.yml"
- import_playbook: "./install_sso.yml"
- import_playbook: "./install_infra.yml"
- import_playbook: "./install_fuse_managed.yml"
- import_playbook: "./install_services.yml"
- import_playbook: "./install_mdc.yml"
- import_playbook: "./install_webapp.yml"
- import_playbook: "./install_middleware_monitoring.yml"
- import_playbook: "./install_application_metrics.yml"
- import_playbook: "./install_user_rhsso.yml"
- import_playbook: "./generate-customisation-inventory.yml"
- import_playbook: "./customise_web_console_install.yml"
- import_playbook: "./apply_ocp_roles.yml"
- import_playbook: "./apply_mdc_manifest.yml"

- hosts: master
  gather_facts: no
  tasks:
    - name: remove integreatly-admin user
      shell: "htpasswd -D /etc/origin/master/htpasswd integreatly-admin"
      become: yes
      when: (run_master_tasks | default(true) | bool) and (create_cluster_admin == true)

- import_playbook: ./install_backups.yml
  when: backup_restore_install | default(false) | bool

- hosts: localhost
  gather_facts: no
  tasks:
    - name: switch back to system admin
      shell: oc login -u system:admin
      register: oc_cmd
      failed_when: oc_cmd.rc != 0 and oc_cmd.rc != 1
      when: create_cluster_admin
    - debug:
        msg: All services have been provisioned successfully.
    - debug:
        msg: Please add '{{ callback_url }}' as the Authorization callback URL of your GitHub OAuth Application.
      vars:
        callback_url: "{{ launcher_sso_route }}/auth/realms/{{ eval_launcher_sso_realm }}/broker/github/endpoint"
      when: launcher
