---
- hosts: localhost
  gather_facts: no
  roles:
  - role: middleware_monitoring
    when: middleware_monitoring | default(true) | bool
  - role: middleware_monitoring_config
    when: middleware_monitoring | default(true) | bool
  - role: 3scale_config
    when: middleware_monitoring | default(true) | bool
  tasks:
  - include_role:
      name: gitea
      tasks_from: monitoring
    when: (middleware_monitoring | default(true) | bool) and gitea
  - include_role:
      name: webapp
      tasks_from: monitoring
    when: (middleware_monitoring | default(true) | bool) and webapp