---
- hosts: localhost
  gather_facts: no
  roles:
    - role: backup
  tasks:
    - include_vars: ../roles/3scale/defaults/main.yml
    - include_vars: ../roles/resources_backup/defaults/main.yml
    - include_vars: ../roles/enmasse/defaults/main.yml
    - include_vars: ../roles/codeready/defaults/main.yml
    - include_vars: ../roles/fuse_managed/defaults/main.yml
    - include_vars: ../roles/launcher/defaults/main.yml
    - import_tasks: ../roles/3scale/tasks/backup.yml
    - import_tasks: ../roles/resources_backup/tasks/main.yml
    - import_tasks: ../roles/enmasse/tasks/backup.yml
    - import_tasks: ../roles/codeready/tasks/backup.yml
    - import_tasks: ../roles/fuse_managed/tasks/backup.yml
    - import_tasks: ../roles/launcher/tasks/backup.yml
    -
      include_role:
        name: mobile_security_service
        tasks_from: backup.yml
      when:  mobile_security_service | default(false) | bool
    -
      include_role:
        name: rhsso
        tasks_from: backup.yaml
      vars:
        sso_namespace: "{{ eval_rhsso_namespace }}"
      tags: ['rhsso']
    -
      include_role:
        name: rhsso
        tasks_from: backup.yaml
      vars:
        sso_namespace: "{{ eval_user_rhsso_namespace }}"
      tags: ['user_rhsso']
      when: user_rhsso | default(true) | bool
    - include_role:
        name: ups
        tasks_from: backup.yml
      vars:
        ups_patch_backup: true
      tags: ['ups']
      when: ups | default(true) | bool
    - include_role:
        name: backup
        tasks_from: monitoring.yml
      when: backup_restore_monitoring | default(true) | bool
