- hosts: localhost
  tasks:
    - 
      # MDC namespace needs to be deleted first to make sure all the CRs can be removed by their operators
      name: Uninstall Mobile Developer Console (mdc)
      include_role:
        name: mdc
        tasks_from: uninstall.yml
      vars:
        mdc_namespace: "{{ eval_mdc_namespace }}"
      tags: ['mdc']
    - 
      name: Uninstall Mobile Security Service
      include_role:
        name: mobile_security_service
        tasks_from: uninstall_mss.yml
      vars:
        mss_namespace: "{{ eval_mobile_security_service_namespace }}"
      tags: ['mss']
    - 
      name: Uninstall Unified Push Server (ups)
      include_role:
        name: ups
        tasks_from: uninstall.yml
      vars:
        ups_namespace: "{{ eval_ups_namespace }}"
      tags: ['ups']

- hosts: master
  tasks:
    - block:
      - name: Remove mdc cors data
        include_role:
          name: mdc
          tasks_from: uninstall-cors
        tags: ['mdc']
      - name: Restart openshift master services
        shell: "/usr/local/bin/master-restart {{ item }}"
        become: yes
        when: mdc
        with_items:
          - api
          - controllers
      - name: Check if openshift master services are running
        shell: oc get nodes
        register: task_result
        until: task_result.rc == 0
        retries: 6
        delay: 5
        failed_when: task_result.rc != 0
      when: run_master_tasks | default(true) | bool