# This file is re-generated after each release!
# If you need to add tasks that should run on every upgrade, update the template here ../../scripts/upgrade.template.yml
---
- hosts: master
  gather_facts: no
  tasks:
  - include_role:
      name: openshift
      tasks_from: set_master_vars
    when: run_master_tasks | default(true) | bool

# Required for Ansible Tower installs that need to login via oc as a prerequisite
- import_playbook: "./openshift.yml"

- hosts: localhost
  gather_facts: yes
  tasks:
  - include_role:
      name: prerequisites
      tasks_from: upgrade
    vars:
      from_versions:
      - "{{ upgrade_from_version }}"

  - name: Set Upgrade Facts
    set_fact: upgrade_{{ item | replace('-', '') }}=true
    with_items: "{{ upgrade_product_roles }}"

  - name: Upgrade product images
    include_role:
      name: "{{ item }}"
      tasks_from: "upgrade_images"
    with_items: "{{ upgrade_product_roles }}"

# Add product specific upgrade tasks here, make sure to use the "when: upgrade_<product>|bool" condition on any new tasks added!!
#
#    - name: Some Special webapp only upgrade thing
#      include_role:
#        name: webapp
#        tasks_from: upgrade_patch
#      when: upgrade_webapp|bool

  - name: Upgrade CodeReady Workspace to version 2.0.0
    include_role:
      name: codeready
      tasks_from: upgrade_1.2_to_2.0
    when: upgrade_codeready|bool

  - name: Upgrade Alert Manager
    include_role:
      name: middleware_monitoring_config
      tasks_from: upgrade_alert_manager_email

  - name: Expose vars
    include_vars: "../roles/enmasse/defaults/main.yml"

  - name: Add AMQ Online service admin role to customer admin
    include_role:
      name: enmasse
      tasks_from: service_admin.yml

  # Prevent user from linking customer-admin to incorrect account on first login to user-sso
  - name: Obtain user sso token for API calls
    include_role:
      name: rhsso-user
      tasks_from: obtain-user-sso-token.yml

  - name: Disable review and confirming link account
    include_role:
      name: rhsso-user
      tasks_from: disable-idp-review-link-confirm.yml


- name: Apply overrides for resource limits and replica counts
  import_playbook: "./update_resources.yml"
  when: resource_limits_managed | default(true) | bool

#Update product version (should always be last)
- import_playbook: "./generate-customisation-inventory.yml"
