# This file is re-generated after each release!
# If you need to add tasks that should run on every upgrade, update the template here ../../scripts/upgrade.template.yml
---
- hosts: master
  gather_facts: no
  tasks:
  - include_role:
      name: openshift
      tasks_from: set_master_vars
    when: run_master_tasks | default(true) | bool

# Required for Ansible Tower installs that need to login via oc as a prerequisite
- import_playbook: "./openshift.yml"

- hosts: localhost
  gather_facts: yes
  tasks:
  - include_role:
      name: prerequisites
      tasks_from: upgrade
    vars:
      from_versions:
      - "{{ upgrade_from_version }}"

  - name: Set Upgrade Facts
    set_fact: upgrade_{{ item | replace('-', '') }}=true
    with_items: "{{ upgrade_product_roles }}"

  # Fuse images upgrade fails because new image tags don't exist
  #Â I am not sure whether this is needed for minor product releases upgrades
  - name: Upgrade product images
    include_role:
      name: "{{ item }}"
      tasks_from: "upgrade_images"
    with_items: "{{ upgrade_product_roles }}"

# Only set these vars if run_master_tasks is true. false for osd, true for pds
  - set_fact:
      openshift_master_url: "{{ hostvars['EVAL_VARS']['openshift_master_url'] }}"
      openshift_asset_url: "{{ hostvars['EVAL_VARS']['openshift_asset_url'] }}"
    when:
      - run_master_tasks | default(true) | bool

# Add product specific upgrade tasks here, make sure to use the "when: upgrade_<product>|bool" condition on any new tasks added!!
#
#    - name: Some Special webapp only upgrade thing
#      include_role:
#        name: webapp
#        tasks_from: upgrade_patch
#      when: upgrade_webapp|bool

# Solution Explorer
  - name: Webapp upgrade
    include_role:
      name: webapp
      tasks_from: upgrade
    vars:
      rhsso_openshift_master_config_path: "{{ eval_openshift_master_config_path }}"
      rhsso_namespace: "{{ eval_rhsso_namespace }}"
      upgrade_webapp_operator_image: quay.io/integreatly/tutorial-web-app-operator:{{ webapp_operator_release_tag }}
    when: upgrade_webapp|default(false)|bool

  - name: Patch launcher config map to patch launcher.backend.catalog.git.ref
    include_role:
      name: launcher
      tasks_from: upgrade
    when: upgrade_launcher|default(false)|bool

  - name: Include vars for blackbox target update
    include_vars: "../roles/3scale/defaults/main.yml"

  - name: Upgrade Enmasse and AMQ BlackboxTarget Route update
    include_role:
      name: enmasse
      tasks_from: upgrade_1.6_1.7
    when: upgrade_enmasse|default(false)|bool

  - name: Upgrade 3scale to 2.8
    include_role:
      name: 3scale
      tasks_from: upgrade_2.7_to_2.8
    when: upgrade_3scale|default(false)|bool

  - name: Upgrade CodeReady Workspace to version 2.0.0
    include_role:
      name: codeready
      tasks_from: upgrade_1.2_to_2.0
    when: upgrade_codeready|default(false)|bool

  - name: Upgrade Fuse on Openshift
    include_role:
      name: fuse
      tasks_from: upgrade
    when: upgrade_fuse|default(false)|bool

  - name: Upgrade Fuse Online
    include_role:
      name: fuse_managed
      tasks_from: upgrade
    when: upgrade_fuse_managed|default(false)|bool

  - name: Set eval_app_host var
    set_fact:
      eval_app_host: "{{ hostvars['EVAL_VARS']['eval_app_host'] }}"

  - name: Upgrade Apicurito
    include_role:
      name: apicurito
      tasks_from: upgrade
    vars:
      route_suffix: "{{ eval_app_host }}"
    when: upgrade_apicurito|default(false)|bool

  # Managed Service Broker upgrade
  - name: Include SSO vars
    include_vars: "../roles/rhsso/defaults/main.yml"

  - name: Upgrade Managed Service Broker
    include_role:
      name: msbroker
      tasks_from: upgrade
    vars:
      route_suffix: "{{ eval_app_host }}"
      sso_realm: "{{ rhsso_realm }}"
    when: upgrade_fuse_managed|default(false)|bool

  - name: Upgrade Alert Manager
    include_role:
      name: middleware_monitoring_config
      tasks_from: upgrade_alert_manager_email

  - name: Update monitoring alerts
    include_role:
      name: middleware_monitoring_config
      tasks_from: create_alerts

  - name: Expose vars
    include_vars: "../roles/enmasse/defaults/main.yml"

  - name: Add AMQ Online service admin role to customer admin
    include_role:
      name: enmasse
      tasks_from: service_admin.yml


  # Prevent user from linking customer-admin to incorrect account on first login to user-sso
  - name: Obtain user sso token for API calls
    include_role:
      name: rhsso-user
      tasks_from: obtain-user-sso-token.yml

  - name: Disable review and confirming link account
    include_role:
      name: rhsso-user
      tasks_from: disable-idp-review-link-confirm.yml

  # Allow admin users to view 3Scale logs via Kibana
  - name: Add Get Namespaces (3Scale) permission to admin users
    include_role:
      name: 3scale
      tasks_from: admins-view-namespace.yml

  #Ensure integreatly version in webapp cr matches new version (should always be 2nd last)
  - name: Update webapp version information
    include_role:
      name: webapp
      tasks_from: update_version_info

- name: Apply overrides for resource limits and replica counts
  import_playbook: "./update_resources.yml"
  when: resource_limits_managed | default(true) | bool

#Update product version (should always be last)
- import_playbook: "./generate-customisation-inventory.yml"

# The following role requires an up to date manifest so this should be called after generating the customisation inventory playbook
- hosts: localhost
  gather_facts: yes
  tasks:
  - name: Update console links in the app launcher menu
    include_role:
      name: customise-web-console
      tasks_from: upgrade