# This file is re-generated after each release!
# If you need to add tasks that should run on every upgrade, update the template here ../../scripts/upgrade.template.yml
---
- hosts: master
  gather_facts: no
  tasks:
  - include_role:
      name: openshift
      tasks_from: set_master_vars
    when: run_master_tasks | default(true) | bool

# Required for Ansible Tower installs that need to login via oc as a prerequisite
- import_playbook: "./openshift.yml"

- hosts: localhost
  gather_facts: yes
  tasks:
  - include_role:
      name: prerequisites
      tasks_from: upgrade
    vars:
      from_versions:
      - "{{ upgrade_from_version }}"

  - name: Set Upgrade Facts
    set_fact: upgrade_{{ item | replace('-', '') }}=true
    with_items: "{{ upgrade_product_roles }}"

  - name: Upgrade product images
    include_role:
      name: "{{ item }}"
      tasks_from: "upgrade_images"
    with_items: "{{ upgrade_product_roles }}"

# Only set these vars if run_master_tasks is true. false for osd, true for pds
  - set_fact:
      openshift_master_url: "{{ hostvars['EVAL_VARS']['openshift_master_url'] }}"
      openshift_asset_url: "{{ hostvars['EVAL_VARS']['openshift_asset_url'] }}"
    when:
      - run_master_tasks | default(true) | bool

# Add product specific upgrade tasks here, make sure to use the "when: upgrade_<product>|bool" condition on any new tasks added!!
#

#  - name: Some Special webapp only upgrade thing
#      include_role:
#        name: webapp
#        tasks_from: upgrade_patch
#      when: upgrade_webapp|bool

  - name: Upgrade fuse online
    include_role:
      name: fuse_managed
      tasks_from: upgrade
    when: upgrade_fuse_managed|bool

  # Prevent user from linking customer-admin to incorrect account on first login to user-sso
  - name: Obtain user sso token for API calls
    include_role:
      name: rhsso-user
      tasks_from: obtain-user-sso-token.yml

  - name: Disable review and confirming link account 
    include_role:
      name: rhsso-user
      tasks_from: disable-idp-review-link-confirm.yml

# Install Heimdall
- import_playbook: "./install_heimdall.yml"

# Add the relevant heimdall image monitor crs to the namespaces to be monitored as part of the upgrade
- import_playbook: "./install_heimdall_crs.yml"

#Update product version (should always be last)
- import_playbook: "./generate-customisation-inventory.yml"
