# This file is re-generated after each release!
# If you need to add tasks that should run on every upgrade, update the template here ../../scripts/upgrade.template.yml
---
- hosts: master
  gather_facts: no
  tasks:
  - include_role:
      name: openshift
      tasks_from: set_master_vars
    when: run_master_tasks | default(true) | bool

# Required for Ansible Tower installs that need to login via oc as a prerequisite
- import_playbook: "./openshift.yml"

- hosts: localhost
  gather_facts: yes
  tasks:
  - include_role:
      name: prerequisites
      tasks_from: upgrade
    vars:
      from_versions:
      - "{{ upgrade_from_version }}"

  - name: Set Upgrade Facts
    set_fact: upgrade_{{ item | replace('-', '') }}=true
    with_items: "{{ upgrade_product_roles }}"

  - name: Upgrade product images
    include_role:
      name: "{{ item }}"
      tasks_from: "upgrade_images"
    with_items: "{{ upgrade_product_roles }}"

# Only set these vars if run_master_tasks is true. false for osd, true for pds
  - set_fact:
      openshift_master_url: "{{ hostvars['EVAL_VARS']['openshift_master_url'] }}"
      openshift_asset_url: "{{ hostvars['EVAL_VARS']['openshift_asset_url'] }}"
    when:
      - run_master_tasks | default(true) | bool

# Add product specific upgrade tasks here, make sure to use the "when: upgrade_<product>|bool" condition on any new tasks added!!
#
#    - name: Some Special webapp only upgrade thing
#      include_role:
#        name: webapp
#        tasks_from: upgrade_patch
#      when: upgrade_webapp|bool

  # 3Scale Config
  - name: Delete Zync ServiceMonitor
    shell: oc delete servicemonitor {{ threescale_zync_sm_name | default("3scale-zync-servicemonitor") }} -n {{ threescale_namespace }}
    register: zync_sm_output
    failed_when: zync_sm_output.stderr != '' and 'not found' not in zync_sm_output.stderr
    changed_when: zync_sm_output.rc == 0 and 'deleted' in zync_sm_output.stdout

  # Solution Explorer
  - name: Webapp upgrade
    include_role:
      name: webapp
      tasks_from: upgrade
    vars:
      rhsso_openshift_master_config_path: "{{ eval_openshift_master_config_path }}"
      rhsso_namespace: "{{ eval_rhsso_namespace }}"
      upgrade_webapp_operator_image: quay.io/integreatly/tutorial-web-app-operator:{{ webapp_operator_release_tag }}
    when: upgrade_webapp|default(false)|bool
    
  # Prevent user from linking customer-admin to incorrect account on first login to user-sso
  - name: Obtain user sso token for API calls
    include_role:
      name: rhsso-user
      tasks_from: obtain-user-sso-token.yml

  - name: Disable review and confirming link account 
    include_role:
      name: rhsso-user
      tasks_from: disable-idp-review-link-confirm.yml

  - name: Update alert manager configuration
    include_role:
      name: middleware_monitoring_config
      tasks_from: upgrade_alert_manager_email.yml
      
  # Update 3scale from 2.9 to 2.10 
  - name: update from 2.9 to 2.10
    include_role:
      name: 3scale
      tasks_from: upgrade_2.9_to_2.10

#Update product version (should always be last)
  - name: Update webapp version info
    include_role:
      name: webapp
      tasks_from: update_version_info.yml

- import_playbook: "./generate-customisation-inventory.yml"
